[theme]
base="dark"
primaryColor="#F8B88B"
backgroundColor="#0E1117"
secondaryBackgroundColor="#252528"
textColor="white"
font="sans serif"
showWidgetBorders=true
baseRadius="5px"
buttonRadius="10px"

[theme.sidebar]
backgroundColor="#F8B88B"
textColor="#000000"

