class ConfigData:
    DB_NAME = "fundDB"
    COLLECTION_NAME = "insights"
    TABLE_SCHEMA = """
        "_id": "ObjectId",
        "fund_id": "string",
        "fund_name": "string",
        "cleaned_data": {
            "performance_tag": "string",
            "Volatility_tag": "string",
            "risk_adjusted_returns": "string",
            "market_sensitivity": "string",
            "downside_protection": "string",
            "cost_efficiency": "string",
            "alpha_status": "string",
            "consistency": "string",
            "sector_info": {
                "sector_bias": "string",
                "sector_leadership": "string",
                "dominant_sector": "array of strings",
                "concentration_risk": "string"
            },
            "reasons_to_invest": "array of strings",
            "reasons_to_avoid": "array of strings"
        },
        "timestamp": "date"
"""
    SCHEMA_DESCRIPTION = """
       Here is the description to determine what each key represents:
        1. _id:
            - Description: Unique identifier for the document.
            - Data Type: ObjectId

        2. fund_id:
            - Description: Unique code identifying the mutual fund.
            - Data Type: String

        3. fund_name:
            - Description: Name of the mutual fund.
            - Data Type: String

        4. cleaned_data:
            - Description: Analytical and classification metadata for the fund.
            - Data Type: Embedded Document
            - Fields:
                a. performance_tag:
                    - Description: Indicates whether the fund is outperforming or underperforming the benchmark.
                    - Data Type: String
                b. Volatility_tag:
                    - Description: Categorization of the fund's volatility (low_volatility, moderate_volatility, high_volatility).
                    - Data Type: String
                c. risk_adjusted_returns:
                    - Description: Quality of returns adjusted for risk (e.g., Poor, Average, Good).
                    - Data Type: String
                d. market_sensitivity:
                    - Description: Sensitivity of the fund relative to the market (e.g., less_volatile_than_market,more_volatile_than_market).
                    - Data Type: String
                e. downside_protection:
                    - Description: How well the fund protects against downside risks (e.g., excellent, weak,good).
                    - Data Type: String
                f. cost_efficiency:
                    - Description: Indicates whether the fund is low-cost or high-cost.(eg.low_cost_fund , high_cost_fund)
                    - Data Type: String
                g. alpha_status:
                    - Description: Alpha generated by the fund (positive_alpha or negative_alpha).
                    - Data Type: String
                h. consistency:
                    - Description: Performance consistency (e.g., long_term_outperformer, lagging_consistency,short_term_outperformer).
                    - Data Type: String
                i. sector_info:
                    - Description: Information about the sector exposure of the fund.
                    - Data Type: Embedded Document
                    - Fields:
                        - sector_bias:
                            - Description: Type of sector bias (e.g.,growth-oriented ,defensive ).
                            - Data Type: String
                        - sector_leadership:
                            - Description: Leading sector or rating (e.g., AAA).
                            - Data Type: String
                        - dominant_sector:
                            - Description: List of dominant sectors in portfolio (e.g., AAA, SOV).
                            - Data Type: Array of Strings
                        - concentration_risk:
                            - Description: Indicates concentration level (e.g., highly_concentrated,moderately_concentrated).
                            - Data Type: String
                j. reasons_to_invest:
                    - Description: Key reasons to invest in the fund.
                    - Data Type: Array of Strings
                k. reasons_to_avoid:
                    - Description: Key reasons to avoid the fund.
                    - Data Type: Array of Strings
        5. timestamp:
            - Description: The date when the fund record was inserted or updated.
            - Data Type: Date
        """
    FEW_SHOT_EXAMPLE_1 = [
        {"$match": {"cleaned_data.performance_tag": "Outperforming_Benchmark"}},
        {"$project": {"fund_id": 1, "fund_name": 1, "_id": 0}},
    ]
    json_ex_2 = [
        {
            "$search": {
                "index": "default",
                "compound": {
                    "should": [
                        {
                            "text": {
                                "query": "sbi bse 100 etf",
                                "path": "fund_name",
                                "fuzzy": {"maxEdits": 2, "prefixLength": 2},
                            }
                        },
                        {
                            "text": {
                                "query": "360 one focussed dir",
                                "path": "fund_name",
                                "fuzzy": {"maxEdits": 2, "prefixLength": 2},
                            }
                        },
                    ]
                },
            }
        },
        {
            "$project": {
                "fund_name": 1,
                "fund_id": 1,
                "cleaned_data": 1,
                "score": {"$meta": "searchScore"},
                "_id": 0,
            }
        },
        {"$sort": {"score": -1}},
        {"$limit": 2},
    ]
